language: php

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install

script:
  - php vendor/bin/phpstan analyse -c .phpstan.neon -l 7 src
  - php vendor/bin/phpunit tests

