language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - PHPSTAN=0

matrix:
  fast_finish: true
  include:
    - php: 7
      env: PHPSTAN=1

before_script:
  - composer self-update
  - if [[ $PHPSTAN = 0 ]] ; composer remove --dev phpstan/phpstan; fi
  - composer install

script:
  - if [[ $PHPSTAN = 1 ]] ; php vendor/bin/phpstan analyse -c .phpstan.neon -l 7 src; fi
  - php vendor/bin/phpunit tests

